version: '3.1'

services:

  db:
    container_name: jwt_flow_pg
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: jwt_flow
      POSTGRES_PASSWORD: jwt_flow
